mysql:
  image: mysql:5.5
  environment:
    - MYSQL_PASS=123
  volumes_from:
    - db:rw
  restart: always

db:
  image: ubuntu:trusty

phpmyadmin:
  image: phpmyadmin
  environment:
    - MYSQL_PASSWORD=123
  links:
    - mysql:mysql
  ports:
    - "80:80"
  restart: always
